apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-deployment
spec:
  replicas: 4
  strategy:
    type: Recreate   # 🔥 Ensures old pod is killed before new one starts
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      containers:
      - name: eks-app
        image: eks-app:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        # envFrom:
        # - configMapRef:
        #     name: app-config
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 120
          periodSeconds: 20
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eks-app-service
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30081
  selector:
    app: eks-app
